version: "3.9"

services:
  app:
    build:
      context: .
    image: reminder_app:latest
    container_name: reminder_app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - gems:/gems
    environment:
      RAILS_ENV: development
      DATABASE_URL: "postgresql://postgres:password@db:5432/reminder_app_development"
      REDIS_URL: "redis://redis:6379/0"
    depends_on:
      - db
      - redis
    command: bundle exec rails server -b 0.0.0.0 -p 3000

  sidekiq:
    build:
      context: .
    image: reminder_app:latest
    container_name: sidekiq
    volumes:
      - .:/app
      - gems:/gems
    depends_on:
      - redis
      - db
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://redis:6379/0
      DATABASE_URL: postgresql://postgres:password@db:5432/reminder_app_development
    command: bundle exec sidekiq

  db:
    image: postgres:14
    container_name: reminder_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  redis:
    image: redis:7
    container_name: reminder_redis
    ports:
      - "6379:6379"

volumes:
  db_data:
  gems:
