default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: reminder_app_development

test:
  <<: *default
  database: reminder_app_test

production:
  <<: *default
  database: reminder_app_production
  username: reminder_app
  password: <%= ENV["POSTGRES_PASSWORD"] %>
